[package]
name = "gossiprs"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1"
rand = { version = "0.9.1" }
serde = { version="1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140" }
tokio = { version = "1", features = ["full"] }